### ISSUE TITLE
behaviour difference to win32/macos sorting behaviour

### ISSUE THREAD

**Issue by timblechmann** [scopeInfinity/NaturalSort#3]
the results returned from the native macos/win32, as well as `ls -v` performs a sorting that, numbers are less than letters, while in this implementation, numbers are greater than letters:

output of `ls`:
```
20xx
xx20
```

output of the implementation:
```
xx20
20xx
```

what would be the best way to approach this? a fix would be a functional change, however the implementation would be in line with the standard behavior

**Comment by scopeInfinity** [comment]
@timblechmann Thanks for pointing it out.
I guess bug is while performing comparision of non-digit character with a digit character.

It can be fixed by replacing Line 199 [Here](https://github.com/scopeInfinity/NaturalSort/blob/master/natural_sort.hpp#L199)
`if( !isdigit(*current1 ) && !isdigit(*current2))` with
`if( !isdigit(*current1 ) || !isdigit(*current2))`
i.e. Perform normal comparision if any of character is non digit character
				
Is this what you meant?

**Comment by scopeInfinity** [comment]
@timblechmann Thanks for pointing it out.
I guess bug is while comparing character with a digit.

It can be fixed by replacing Line 199 ([here](https://github.com/scopeInfinity/NaturalSort/blob/master/natural_sort.hpp#L199))
`if( !isdigit(*current1 ) && !isdigit(*current2))` with
`if( !isdigit(*current1 ) || !isdigit(*current2))`
i.e. If any of character is non digit execute normal comparision

Is this what you meant?

**Comment by scopeInfinity** [comment]
@timblechmann Thanks for pointing it out.
I guess bug is while performing comparision of character with a digit.

It can be fixed by replacing Line 199 [Here](https://github.com/scopeInfinity/NaturalSort/blob/master/natural_sort.hpp#L199)
`if( !isdigit(*current1 ) && !isdigit(*current2))` with
`if( !isdigit(*current1 ) || !isdigit(*current2))`

Is this what you meant?

**Comment by timblechmann** [comment]
@scopeInfinity thanks for the quick reply. yes, this change seems to provide the same behavior as the other implementations.
